-- Owners deliberately have no row here: "no credit" is modelled as the absence
-- of a wallet, so the rule is enforced by the schema and not only by code.
CREATE TABLE credit_balances (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL,
    balance           INTEGER     NOT NULL DEFAULT 0,
    version           BIGINT      NOT NULL DEFAULT 0,
    last_recharged_at TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL,
    updated_at        TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_credit_balances_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_credit_balances_user UNIQUE (user_id),
    CONSTRAINT ck_credit_balances_non_negative CHECK (balance >= 0)
);

-- Append-only ledger. Corrections are new ADJUSTMENT rows, never updates.
CREATE TABLE credit_transactions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL,
    type           VARCHAR(30) NOT NULL,
    amount         INTEGER     NOT NULL,
    balance_before INTEGER     NOT NULL,
    balance_after  INTEGER     NOT NULL,
    reference_type VARCHAR(50),
    reference_id   BIGINT,
    description    VARCHAR(255),
    created_at     TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_credit_transactions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_credit_transactions_type CHECK (
        type IN ('INITIAL_GRANT', 'MONTHLY_RECHARGE', 'INQUIRY_DEDUCTION', 'ADJUSTMENT')),
    CONSTRAINT ck_credit_transactions_balance CHECK (balance_after = balance_before + amount),
    CONSTRAINT ck_credit_transactions_non_negative CHECK (balance_before >= 0 AND balance_after >= 0)
);

CREATE INDEX ix_credit_transactions_user_created ON credit_transactions (user_id, created_at DESC);
CREATE INDEX ix_credit_transactions_type_created ON credit_transactions (type, created_at);
