CREATE TABLE kosts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id         BIGINT         NOT NULL,
    name             VARCHAR(150)   NOT NULL,
    description      TEXT,
    address_street   VARCHAR(255)   NOT NULL,
    address_district VARCHAR(100)   NOT NULL,
    address_city     VARCHAR(100)   NOT NULL,
    address_province VARCHAR(100)   NOT NULL,
    postal_code      VARCHAR(10),
    latitude         NUMERIC(10, 8),
    longitude        NUMERIC(11, 8),
    price_per_month  NUMERIC(12, 2) NOT NULL,
    room_type        VARCHAR(20)    NOT NULL,
    total_rooms      INTEGER        NOT NULL,
    available_rooms  INTEGER        NOT NULL,
    is_active        BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ    NOT NULL,
    updated_at       TIMESTAMPTZ    NOT NULL,
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT fk_kosts_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT ck_kosts_room_type CHECK (room_type IN ('PUTRA', 'PUTRI', 'CAMPUR')),
    CONSTRAINT ck_kosts_price_positive CHECK (price_per_month > 0),
    CONSTRAINT ck_kosts_total_rooms_positive CHECK (total_rooms > 0),
    CONSTRAINT ck_kosts_available_rooms_within_capacity
        CHECK (available_rooms >= 0 AND available_rooms <= total_rooms)
);

CREATE TABLE kost_facilities (
    kost_id BIGINT      NOT NULL,
    name    VARCHAR(50) NOT NULL,
    CONSTRAINT pk_kost_facilities PRIMARY KEY (kost_id, name),
    CONSTRAINT fk_kost_facilities_kost FOREIGN KEY (kost_id) REFERENCES kosts (id) ON DELETE CASCADE
);

CREATE TABLE kost_photos (
    kost_id    BIGINT       NOT NULL,
    url        VARCHAR(500) NOT NULL,
    sort_order INTEGER      NOT NULL,
    CONSTRAINT pk_kost_photos PRIMARY KEY (kost_id, sort_order),
    CONSTRAINT fk_kost_photos_kost FOREIGN KEY (kost_id) REFERENCES kosts (id) ON DELETE CASCADE
);
