CREATE TABLE availability_inquiries (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kost_id                  BIGINT      NOT NULL,
    user_id                  BIGINT      NOT NULL,
    message                  TEXT,
    credit_charged           INTEGER     NOT NULL,
    available_rooms_snapshot INTEGER     NOT NULL,
    status                   VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    owner_reply              TEXT,
    replied_at               TIMESTAMPTZ,
    created_at               TIMESTAMPTZ NOT NULL,
    updated_at               TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_inquiries_kost FOREIGN KEY (kost_id) REFERENCES kosts (id),
    CONSTRAINT fk_inquiries_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_inquiries_status CHECK (status IN ('PENDING', 'ANSWERED')),
    CONSTRAINT ck_inquiries_credit_charged CHECK (credit_charged >= 0)
);

CREATE INDEX ix_inquiries_user_created ON availability_inquiries (user_id, created_at DESC);
CREATE INDEX ix_inquiries_kost_status ON availability_inquiries (kost_id, status);
